name: java ci pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn clean package
    - name: Upload Artifact
      if: success()  # Only execute if previous steps were successful
      uses: actions/upload-artifact@v3
      with:
        name: insured-assurance-war
        path: "target/insuredassurance-1.0.war"
        if-no-files-found: error  # Fail the workflow if no files are found to upload
