name: java ci pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Jenkins Job Trigger
      if: success()  # Only execute if previous steps were successful
      uses: estherk0/jenkins-trigger@1.0
      with:
        url: http://34.228.156.254:8080/job/test/build?token=test
        api_token: ${{ secrets.JENKINS_TOKEN }}
        user_name: admin
        job_name: test 
