name: java ci pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup Maven Action
      uses: s4u/setup-maven-action@v1.7.0
      with:
        checkout-fetch-depth: 0
        java-version: 17
        java-distribution: temurin
        maven-version: 3.9.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Upload Artifact
      if: success()  # Only execute if previous steps were successful
      uses: actions/upload-artifact@v4
      with:
        name: insured-assurance-war
        path: "target/insuredassurance.war"
        if-no-files-found: error  # Fail the workflow if no files are found to upload
