name: secret test

on:
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    environment: jenkinsdeploy
    steps:
     - name: Debug Environment
       run: |
         echo "Token length: ${TOKEN_LENGTH}"
       env:
          TOKEN_LENGTH: ${{ secrets.JENKINS_TOKEN }}
