name: secret test

on:
  workflow_dispatch:

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Environment
        run: echo "Token is ${#secrets.JENKINS_TOKEN} characters long"
